
const freelancerdata = 
    [
        {
            "id": 1,
            "track": "Web Development",
            "description": "I will develop and maintain websites, ensuring they are user-friendly and functional. This track prepares me for roles in a high-demand industry, where my skills will help businesses establish their online presence.",
            "image": "https://img.freepik.com/free-photo/portrait-man-laughing_23-2148859448.jpg?size=338&ext=jpg&ga=GA1.1.2113030492.1728950400&semt=ais_hybrid",
            "name": "Mohamed",
            "company": "IT Wizz",
            "phone": "123-456-7890",
            "email": "mohamed@gmail.com",
            "facebook": "https://www.facebook.com/fansoffreelancer/",
            "twitter": "https://x.com/freelancer",
            "linkedin": "https://www.linkedin.com/company/freelancer-com/?originalSubdomain=au",
            "instagram": "https://www.instagram.com/freelancerofficial/",
            "languages": "Arabic, English",
            "from": "Egypt",
            "Certifications": "Certified Web Developer from Egypt"
        },
        {
            "id": 2,
            "track": "AI Development",
            "description": "I will create intelligent systems that learn from data and improve over time. This track is crucial for organizations looking to harness the power of AI, making my expertise valuable as the field grows.",
            "image": "https://img.freepik.com/free-photo/portrait-man-laughing_23-2148859448.jpg?size=338&ext=jpg&ga=GA1.1.2113030492.1728950400&semt=ais_hybrid",
            "name": "Ahmed",
            "company": "RoboTech",
            "phone": "987-654-3210",
            "email": "ahmed@gmail.com",
            "facebook": "https://www.facebook.com/fansoffreelancer/",
            "twitter": "https://x.com/freelancer",
            "linkedin": "https://www.linkedin.com/company/freelancer-com/?originalSubdomain=au",
            "instagram": "https://www.instagram.com/freelancerofficial/",
            "languages": "Arabic, French, English",
            "from": "Morocco",
            "Certifications": "AI Specialist from Morocco"
        },
        {
            "id": 3,
            "track": "Website Platform",
            "description": "I will manage and optimize content management systems like WordPress. This skill is essential for businesses seeking to create and maintain effective online platforms.",
            "image": "https://img.freepik.com/free-photo/portrait-man-laughing_23-2148859448.jpg?size=338&ext=jpg&ga=GA1.1.2113030492.1728950400&semt=ais_hybrid",
            "name": "Ali",
            "company": "SiteMaster",
            "phone": "111-222-3333",
            "email": "ali@gmail.com",
            "facebook": "https://www.facebook.com/fansoffreelancer/",
            "twitter": "https://x.com/freelancer",
            "linkedin": "https://www.linkedin.com/company/freelancer-com/?originalSubdomain=au",
            "instagram": "https://www.instagram.com/freelancerofficial/",
            "languages": "Arabic, Turkish, English",
            "from": "Turkey",
            "Certifications": "WordPress Administrator from Turkey"
        },
        {
            "id": 4,
            "track": "Mobile App Development",
            "description": "I will design and develop mobile applications for various platforms. This track is ideal for tapping into the growing market of mobile users, making my skills highly sought after.",
            "image": "https://img.freepik.com/free-photo/portrait-man-laughing_23-2148859448.jpg?size=338&ext=jpg&ga=GA1.1.2113030492.1728950400&semt=ais_hybrid",
            "name": "Yossef",
            "company": "Smart Apps Co.",
            "phone": "444-555-6666",
            "email": "karim@gmail.com",
            "facebook": "https://www.facebook.com/fansoffreelancer/",
            "twitter": "https://x.com/freelancer",
            "linkedin": "https://www.linkedin.com/company/freelancer-com/?originalSubdomain=au",
            "instagram": "https://www.instagram.com/freelancerofficial/",
            "languages": "French, Arabic, English",
            "from": "Algeria",
            "Certifications": "Mobile App Developer from Algeria"
        },
        {
            "id": 5,
            "track": "Chatbot Development",
            "description": "I will design and build chatbots for customer service, sales, and support, offering businesses innovative ways to engage with their users.",
            "image": "https://img.freepik.com/free-photo/portrait-man-laughing_23-2148859448.jpg?size=338&ext=jpg&ga=GA1.1.2113030492.1728950400&semt=ais_hybrid",
            "name": "Tamer",
            "company": "AI Bots Ltd.",
            "phone": "555-444-3333",
            "email": "layla@gmail.com",
            "facebook": "https://www.facebook.com/fansoffreelancer/",
            "twitter": "https://x.com/freelancer",
            "linkedin": "https://www.linkedin.com/company/freelancer-com/?originalSubdomain=au",
            "instagram": "https://www.instagram.com/freelancerofficial/",
            "languages": "English, Arabic",
            "from": "Jordan",
            "Certifications": "Certified Chatbot Developer from Jordan"
        },
        {
            "id": 6,
            "track": "Game Development",
            "description": "I will create immersive video games for various platforms. This skill is highly rewarding for those who aim to entertain and innovate in the gaming industry.",
            "image": "https://img.freepik.com/free-photo/portrait-man-laughing_23-2148859448.jpg?size=338&ext=jpg&ga=GA1.1.2113030492.1728950400&semt=ais_hybrid",
            "name": "Maged",
            "company": "GameCraft",
            "phone": "777-888-9999",
            "email": "sara@gmail.com",
            "facebook": "https://www.facebook.com/fansoffreelancer/",
            "twitter": "https://x.com/freelancer",
            "linkedin": "https://www.linkedin.com/company/freelancer-com/?originalSubdomain=au",
            "instagram": "https://www.instagram.com/freelancerofficial/",
            "languages": "English, Spanish, Arabic",
            "from": "Spain",
            "Certifications": "Game Development Specialist from Spain"
        },
        {
            "id": 7,
            "track": "Data Science",
            "description": "I will analyze and interpret complex data to help organizations make informed decisions.",
            "image": "https://img.freepik.com/free-photo/portrait-man-laughing_23-2148859448.jpg?size=338&ext=jpg&ga=GA1.1.2113030492.1728950400&semt=ais_hybrid",
            "name": "Omar",
            "company": "DataPro",
            "phone": "123-987-6543",
            "email": "omar@gmail.com",
            "facebook": "https://www.facebook.com/fansoffreelancer/",
            "twitter": "https://x.com/freelancer",
            "linkedin": "https://www.linkedin.com/company/freelancer-com/?originalSubdomain=au",
            "instagram": "https://www.instagram.com/freelancerofficial/",
            "languages": "Arabic, English",
            "from": "Egypt",
            "Certifications": "Data Science Professional from Egypt"
        },
        {
            "id": 8,
            "track": "Graphic Design",
            "description": "I will create visual content that communicates ideas effectively. This skill is indispensable for businesses needing branding and marketing materials.",
            "image": "https://img.freepik.com/free-photo/portrait-man-laughing_23-2148859448.jpg?size=338&ext=jpg&ga=GA1.1.2113030492.1728950400&semt=ais_hybrid",
            "name": "Mrwan",
            "company": "DesignPro",
            "phone": "321-654-9870",
            "email": "fatima@gmail.com",
            "facebook": "https://www.facebook.com/fansoffreelancer/",
            "twitter": "https://x.com/freelancer",
            "linkedin": "https://www.linkedin.com/company/freelancer-com/?originalSubdomain=au",
            "instagram": "https://www.instagram.com/freelancerofficial/",
            "languages": "Arabic, French, English",
            "from": "Tunisia",
            "Certifications": "Graphic Design Expert from Tunisia"
        },
        {
            "id": 9,
            "track": "Digital Marketing",
            "description": "I will develop and execute marketing strategies to enhance online visibility and drive business growth.",
            "image": "https://img.freepik.com/free-photo/portrait-man-laughing_23-2148859448.jpg?size=338&ext=jpg&ga=GA1.1.2113030492.1728950400&semt=ais_hybrid",
            "name": "Hassan",
            "company": "MarketGenius",
            "phone": "999-888-7777",
            "email": "hassan@gmail.com",
            "facebook": "https://www.facebook.com/fansoffreelancer/",
            "twitter": "https://x.com/freelancer",
            "linkedin": "https://www.linkedin.com/company/freelancer-com/?originalSubdomain=au",
            "instagram": "https://www.instagram.com/freelancerofficial/",
            "languages": "Arabic, English",
            "from": "UAE",
            "Certifications": "Certified Digital Marketer from UAE"
        },
        {
            "id": 10,
            "track": "Web Development",
            "description": "I will build responsive and user-friendly websites to enhance online presence for businesses and individuals.",
            "image": "https://img.freepik.com/free-photo/portrait-man-laughing_23-2148859448.jpg?size=338&ext=jpg&ga=GA1.1.2113030492.1728950400&semt=ais_hybrid",
            "name": "Ahmed",
            "company": "WebCraft",
            "phone": "555-666-7777",
            "email": "ahmed@gmail.com",
            "facebook": "https://www.facebook.com/fansoffreelancer/",
            "twitter": "https://x.com/freelancer",
            "linkedin": "https://www.linkedin.com/company/freelancer-com/?originalSubdomain=au",
            "instagram": "https://www.instagram.com/freelancerofficial/",
            "languages": "Arabic, English",
            "from": "Egypt",
            "Certifications": "Certified Web Developer from Egypt"
        },
        {
            "id": 11,
            "track": "Mobile App Development",
            "description": "I will develop engaging and feature-rich mobile applications for both Android and iOS platforms.",
            "image": "https://img.freepik.com/free-photo/portrait-man-laughing_23-2148859448.jpg?size=338&ext=jpg&ga=GA1.1.2113030492.1728950400&semt=ais_hybrid",
            "name": "Ali",
            "company": "AppMasters",
            "phone": "888-777-6666",
            "email": "ali@gmail.com",
            "facebook": "https://www.facebook.com/fansoffreelancer/",
            "twitter": "https://x.com/freelancer",
            "linkedin": "https://www.linkedin.com/company/freelancer-com/?originalSubdomain=au",
            "instagram": "https://www.instagram.com/freelancerofficial/",
            "languages": "English, Arabic",
            "from": "Kuwait",
            "Certifications": "Mobile App Developer from Kuwait"
        },
        {
            "id": 12,
            "track": "Cybersecurity",
            "description": "I will implement security measures to protect businesses from online threats and ensure data integrity.",
            "image": "https://img.freepik.com/free-photo/portrait-man-laughing_23-2148859448.jpg?size=338&ext=jpg&ga=GA1.1.2113030492.1728950400&semt=ais_hybrid",
            "name": "Slem",
            "company": "SecureTech",
            "phone": "111-222-3333",
            "email": "salma@gmail.com",
            "facebook": "https://www.facebook.com/fansoffreelancer/",
            "twitter": "https://x.com/freelancer",
            "linkedin": "https://www.linkedin.com/company/freelancer-com/?originalSubdomain=au",
            "instagram": "https://www.instagram.com/freelancerofficial/",
            "languages": "English, French, Arabic",
            "from": "Morocco",
            "Certifications": "Certified Cybersecurity Specialist from Morocco"
        },
        {
            "id": 13,
            "track": "SEO Optimization",
            "description": "I will enhance website visibility and traffic through effective search engine optimization techniques.",
            "image": "https://img.freepik.com/free-photo/portrait-man-laughing_23-2148859448.jpg?size=338&ext=jpg&ga=GA1.1.2113030492.1728950400&semt=ais_hybrid",
            "name": "Yassen",
            "company": "SEO Experts",
            "phone": "444-555-6666",
            "email": "yasmin@gmail.com",
            "facebook": "https://www.facebook.com/fansoffreelancer/",
            "twitter": "https://x.com/freelancer",
            "linkedin": "https://www.linkedin.com/company/freelancer-com/?originalSubdomain=au",
            "instagram": "https://www.instagram.com/freelancerofficial/",
            "languages": "Arabic, English",
            "from": "Jordan",
            "Certifications": "Certified SEO Specialist from Jordan"
        },
        {
            "id": 14,
            "track": "Content Writing",
            "description": "I will craft compelling and engaging content for blogs, websites, and marketing materials.",
            "image": "https://img.freepik.com/free-photo/portrait-man-laughing_23-2148859448.jpg?size=338&ext=jpg&ga=GA1.1.2113030492.1728950400&semt=ais_hybrid",
            "name": "Amir",
            "company": "Content Pros",
            "phone": "777-888-5555",
            "email": "amal@gmail.com",
            "facebook": "https://www.facebook.com/fansoffreelancer/",
            "twitter": "https://x.com/freelancer",
            "linkedin": "https://www.linkedin.com/company/freelancer-com/?originalSubdomain=au",
            "instagram": "https://www.instagram.com/freelancerofficial/",
            "languages": "Arabic, English, Spanish",
            "from": "Lebanon",
            "Certifications": "Content Writing Expert from Lebanon"
        },
        {
            "id": 15,
            "track": "Machine Learning",
            "description": "I will design and implement machine learning models to solve real-world problems.",
            "image": "https://img.freepik.com/free-photo/portrait-man-laughing_23-2148859448.jpg?size=338&ext=jpg&ga=GA1.1.2113030492.1728950400&semt=ais_hybrid",
            "name": "Khalid",
            "company": "AI Solutions",
            "phone": "123-456-7890",
            "email": "khalid@gmail.com",
            "facebook": "https://www.facebook.com/fansoffreelancer/",
            "twitter": "https://x.com/freelancer",
            "linkedin": "https://www.linkedin.com/company/freelancer-com/?originalSubdomain=au",
            "instagram": "https://www.instagram.com/freelancerofficial/",
            "languages": "Arabic, English",
            "from": "Saudi Arabia",
            "Certifications": "Machine Learning Specialist from Saudi Arabia"
        },
        {
            "id": 16,
            "track": "Cloud Computing",
            "description": "I will help businesses migrate to and manage cloud-based solutions for improved scalability and performance.",
            "image": "https://img.freepik.com/free-photo/portrait-man-laughing_23-2148859448.jpg?size=338&ext=jpg&ga=GA1.1.2113030492.1728950400&semt=ais_hybrid",
            "name": "kareem",
            "company": "Cloud Gurus",
            "phone": "333-444-5555",
            "email": "noor@gmail.com",
            "facebook": "https://www.facebook.com/fansoffreelancer/",
            "twitter": "https://x.com/freelancer",
            "linkedin": "https://www.linkedin.com/company/freelancer-com/?originalSubdomain=au",
            "instagram": "https://www.instagram.com/freelancerofficial/",
            "languages": "Arabic, French, English",
            "from": "Algeria",
            "Certifications": "Cloud Computing Specialist from Algeria"
        },
        {
            "id": 17,
            "track": "UI/UX Design",
            "description": "I will create intuitive and visually appealing user interfaces and experiences.",
            "image": "https://img.freepik.com/free-photo/portrait-man-laughing_23-2148859448.jpg?size=338&ext=jpg&ga=GA1.1.2113030492.1728950400&semt=ais_hybrid",
            "name": "Rame",
            "company": "Design Vision",
            "phone": "555-123-4567",
            "email": "reem@gmail.com",
            "facebook": "https://www.facebook.com/fansoffreelancer/",
            "twitter": "https://x.com/freelancer",
            "linkedin": "https://www.linkedin.com/company/freelancer-com/?originalSubdomain=au",
            "instagram": "https://www.instagram.com/freelancerofficial/",
            "languages": "Arabic, English",
            "from": "Bahrain",
            "Certifications": "UI/UX Design Specialist from Bahrain"
        },
        {
            "id": 18,
            "track": "Blockchain Development",
            "description": "I will develop and maintain blockchain applications to drive innovation in decentralized systems.",
            "image": "https://img.freepik.com/free-photo/portrait-man-laughing_23-2148859448.jpg?size=338&ext=jpg&ga=GA1.1.2113030492.1728950400&semt=ais_hybrid",
            "name": "Samir",
            "company": "Blockchain Innovators",
            "phone": "999-777-8888",
            "email": "samir@gmail.com",
            "facebook": "https://www.facebook.com/fansoffreelancer/",
            "twitter": "https://x.com/freelancer",
            "linkedin": "https://www.linkedin.com/company/freelancer-com/?originalSubdomain=au",
            "instagram": "https://www.instagram.com/freelancerofficial/",
            "languages": "Arabic, English",
            "from": "Qatar",
            "Certifications": "Blockchain Development Specialist from Qatar"
        }
    ];
      
    
export default freelancerdata;









