const WebDevelopment = [
    {
        "id": 1,
        "track": "Business Websites",
        "description": "I specialize in creating tailored business websites that effectively represent your brand online.",
        "image": "https://img.freepik.com/free-photo/portrait-businessman_23-2148859448.jpg?size=338&ext=jpg&ga=GA1.1.2113030492.1728950400&semt=ais_hybrid",
        "profileimage": "https://img.freepik.com/free-photo/man-suit_23-2148859400.jpg?size=338&ext=jpg&ga=GA1.1.2113030492.1728950400&semt=ais_hybrid",
        "name": "Mohamed Ali",
        "company": "Web Innovators",
        "phone": "321-654-0987",
        "email": "mohamed.ali@gmail.com",
        "facebook": "https://www.facebook.com/mohamedali",
        "twitter": "https://x.com/mohamedali",
        "linkedin": "https://www.linkedin.com/in/mohamedali/",
        "languages": "Arabic, English, French",
        "from": "Egypt",
        "Certifications": "Certified Web Specialist from Egypt"
    },
    {
        "id": 2,
        "track": "E-Commerce Development",
        "description": "I develop robust e-commerce platforms that drive sales and enhance customer experiences.",
        "image": "https://img.freepik.com/free-photo/portrait-ecommerce-expert_23-2148859448.jpg?size=338&ext=jpg&ga=GA1.1.2113030492.1728950400&semt=ais_hybrid",
        "profileimage": "https://img.freepik.com/free-photo/man-business-casual_23-2148859401.jpg?size=338&ext=jpg&ga=GA1.1.2113030492.1728950400&semt=ais_hybrid",
        "name": "Ahmed Ben",
        "company": "E-Com Solutions",
        "phone": "456-789-0123",
        "email": "ahmed.ben@gmail.com",
        "facebook": "https://www.facebook.com/ahmedben",
        "twitter": "https://x.com/ahmedben",
        "linkedin": "https://www.linkedin.com/in/ahmedben/",
        "languages": "Arabic, French, English",
        "from": "Morocco",
        "Certifications": "E-Commerce Developer Certification from Morocco"
    },
    {
        "id": 3,
        "track": "Landing Pages",
        "description": "I create high-converting landing pages designed to capture leads and maximize conversions.",
        "image": "https://img.freepik.com/free-photo/portrait-landing-page-specialist_23-2148859448.jpg?size=338&ext=jpg&ga=GA1.1.2113030492.1728950400&semt=ais_hybrid",
        "profileimage": "https://img.freepik.com/free-photo/man-portrait_23-2148859402.jpg?size=338&ext=jpg&ga=GA1.1.2113030492.1728950400&semt=ais_hybrid",
        "name": "Ali Kadir",
        "company": "Landing Page Pros",
        "phone": "789-012-3456",
        "email": "ali.kadir@gmail.com",
        "facebook": "https://www.facebook.com/alikadir",
        "twitter": "https://x.com/alikadir",
        "linkedin": "https://www.linkedin.com/in/alikadir/",
        "languages": "Arabic, Turkish, English",
        "from": "Turkey",
        "Certifications": "Landing Page Expert Certification from Turkey"
    },
    {
        "id": 4,
        "track": "Dropshipping Websites",
        "description": "I build seamless dropshipping websites that simplify the purchasing process and boost sales.",
        "image": "https://img.freepik.com/free-photo/portrait-dropshipping-expert_23-2148859448.jpg?size=338&ext=jpg&ga=GA1.1.2113030492.1728950400&semt=ais_hybrid",
        "profileimage": "https://img.freepik.com/free-photo/businessman-with-arms-crossed_23-2148859403.jpg?size=338&ext=jpg&ga=GA1.1.2113030492.1728950400&semt=ais_hybrid",
        "name": "Karim Zahir",
        "company": "Dropship Masters",
        "phone": "234-567-8901",
        "email": "karim.zahir@gmail.com",
        "facebook": "https://www.facebook.com/karimzahir",
        "twitter": "https://x.com/karimzahir",
        "linkedin": "https://www.linkedin.com/in/karimzahir/",
        "languages": "French, Arabic, English",
        "from": "Algeria",
        "Certifications": "Dropshipping Certification from Algeria"
    },
    {
        "id": 5,
        "track": "Build a Complete Website",
        "description": "I will design and develop a complete website tailored to your needs, from concept to launch.",
        "image": "https://img.freepik.com/free-photo/portrait-full-stack-developer_23-2148859448.jpg?size=338&ext=jpg&ga=GA1.1.2113030492.1728950400&semt=ais_hybrid",
        "profileimage": "https://img.freepik.com/free-photo/man-formal-suit_23-2148859404.jpg?size=338&ext=jpg&ga=GA1.1.2113030492.1728950400&semt=ais_hybrid",
        "name": "Sami Jamil",
        "company": "Complete Web Solutions",
        "phone": "678-901-2345",
        "email": "sami.jamil@gmail.com",
        "facebook": "https://www.facebook.com/samijamil",
        "twitter": "https://x.com/samijamil",
        "linkedin": "https://www.linkedin.com/in/samijamil/",
        "languages": "English, Arabic",
        "from": "Jordan",
        "Certifications": "Full Stack Developer Certification from Jordan"
    },
    {
        "id": 6,
        "track": "Business Websites",
        "description": "I create efficient business websites to enhance your online presence and attract customers.",
        "image": "https://img.freepik.com/free-photo/portrait-business-developer_23-2148859448.jpg?size=338&ext=jpg&ga=GA1.1.2113030492.1728950400&semt=ais_hybrid",
        "profileimage": "https://img.freepik.com/free-photo/man-portrait-formal_23-2148859405.jpg?size=338&ext=jpg&ga=GA1.1.2113030492.1728950400&semt=ais_hybrid",
        "name": "Hassan Ali",
        "company": "BizWeb Creations",
        "phone": "123-456-7891",
        "email": "hassan.ali@gmail.com",
        "facebook": "https://www.facebook.com/hassanali",
        "twitter": "https://x.com/hassanali",
        "linkedin": "https://www.linkedin.com/in/hassanali/",
        "languages": "Arabic, English",
        "from": "Lebanon",
        "Certifications": "Certified Business Website Developer from Lebanon"
    },
    {
        "id": 7,
        "track": "E-Commerce Development",
        "description": "I build scalable e-commerce websites to help businesses increase their sales.",
        "image": "https://img.freepik.com/free-photo/portrait-ecommerce-developer_23-2148859448.jpg?size=338&ext=jpg&ga=GA1.1.2113030492.1728950400&semt=ais_hybrid",
        "profileimage": "https://img.freepik.com/free-photo/man-business-attire_23-2148859406.jpg?size=338&ext=jpg&ga=GA1.1.2113030492.1728950400&semt=ais_hybrid",
        "name": "Mostafa Khalid",
        "company": "E-Commerce Experts",
        "phone": "234-567-8902",
        "email": "mostafa.khalid@gmail.com",
        "facebook": "https://www.facebook.com/mostafakhalid",
        "twitter": "https://x.com/mostafakhalid",
        "linkedin": "https://www.linkedin.com/in/mostafakhalid/",
        "languages": "Arabic, English, German",
        "from": "Saudi Arabia",
        "Certifications": "E-Commerce Certification from Saudi Arabia"
    },
    {
        "id": 8,
        "track": "Landing Pages",
        "description": "I focus on creating landing pages that are optimized for conversion and lead generation.",
        "image": "https://img.freepik.com/free-photo/portrait-landing-page-creator_23-2148859448.jpg?size=338&ext=jpg&ga=GA1.1.2113030492.1728950400&semt=ais_hybrid",
        "profileimage": "https://img.freepik.com/free-photo/man-with-glasses_23-2148859407.jpg?size=338&ext=jpg&ga=GA1.1.2113030492.1728950400&semt=ais_hybrid",
        "name": "Ziad Omar",
        "company": "Landing Page Agency",
        "phone": "345-678-9012",
        "email": "ziad.omar@gmail.com",
        "facebook": "https://www.facebook.com/ziadomar",
        "twitter": "https://x.com/ziadomar",
        "linkedin": "https://www.linkedin.com/in/ziadomar/",
        "languages": "Arabic, English, Italian",
        "from": "Syria",
        "Certifications": "Landing Page Specialist from Syria"
    },
    {
        "id": 9,
        "track": "Dropshipping Websites",
        "description": "I design and develop dropshipping websites that optimize user experience and sales.",
        "image": "https://img.freepik.com/free-photo/portrait-dropshipping-specialist_23-2148859448.jpg?size=338&ext=jpg&ga=GA1.1.2113030492.1728950400&semt=ais_hybrid",
        "profileimage": "https://img.freepik.com/free-photo/man-business-formal_23-2148859408.jpg?size=338&ext=jpg&ga=GA1.1.2113030492.1728950400&semt=ais_hybrid",
        "name": "Rami Nasr",
        "company": "Dropship Development Co.",
        "phone": "456-789-0123",
        "email": "rami.nasr@gmail.com",
        "facebook": "https://www.facebook.com/raminasr",
        "twitter": "https://x.com/raminasr",
        "linkedin": "https://www.linkedin.com/in/raminasr/",
        "languages": "Arabic, English, Russian",
        "from": "UAE",
        "Certifications": "Dropshipping Expert from UAE"
    },
    {
        "id": 10,
        "track": "Build a Complete Website",
        "description": "I will create a comprehensive website that meets all your business needs.",
        "image": "https://img.freepik.com/free-photo/portrait-web-designer_23-2148859448.jpg?size=338&ext=jpg&ga=GA1.1.2113030492.1728950400&semt=ais_hybrid",
        "profileimage": "https://img.freepik.com/free-photo/man-professional_23-2148859409.jpg?size=338&ext=jpg&ga=GA1.1.2113030492.1728950400&semt=ais_hybrid",
        "name": "Omar Farouk",
        "company": "Web Creations Co.",
        "phone": "444-333-2222",
        "email": "omar.farouk@gmail.com",
        "facebook": "https://www.facebook.com/omarfarouk",
        "twitter": "https://x.com/omarfarouk",
        "linkedin": "https://www.linkedin.com/in/omarfarouk/",
        "languages": "Arabic, English, Spanish",
        "from": "Palestine",
        "Certifications": "Web Development Professional Certification from Palestine"
    }
];
export default WebDevelopment;
